language: ruby
rvm:
  - 2.2.4
  - 2.3.0
  - 2.3.1

before_script:
  - psql -c 'create database bio_test' -U postgres

script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rake db:test:prepare
    - bundle exec rake test
