# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24acb0dc76b3f64caa37907c3f87cd8d678b6f1fb3fb08db53fe3cd3b571f1c582de8f98d4b3b02db60714f021a3e52118f4c9be9b6405004c84bf4bc71be4db

test:
  secret_key_base: dadf660e115bd1cb6670eaa629ae5d888eec175eed234e6978cbb0944b5382f105fe6122cadc1bd4282fc6a1fa92ed7ab4f6fbb44197949493c2f0be55dc8bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
